<?php

declare(strict_types=1);

namespace App\Exception;

use Spiral\Exceptions\ExceptionHandler;

/**
 * -----------------------------------------------------
 * In this file, you can modify the exception handling
 * -----------------------------------------------------
 */
final class Handler extends ExceptionHandler
{
//    protected function handleError(int $errno, string $errstr, string $errfile = '', int $errline = 0,): bool
//    {
//        return parent::handleError($errno, $errstr, $errfile, $errline); // TODO: Change the autogenerated stub
//    }
//
//    public function handleGlobalException(\Throwable $e): void
//    {
//        parent::handleGlobalException($e); // TODO: Change the autogenerated stub
//    }
}
